name: Deploy Calculator-pro Docker App to AWS EC2

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: calculator-repo
  CONTAINER_NAME: calculator-cont
  INSTANCE_TYPE: t2.micro
  AMI_ID: ami-0c398cb65a93047f2
  KEY_NAME: calsi-key
  INSTANCE_NAME: ec-2-instance
  SECURITY_GROUP_NAME: launch-wizard-6
  SECURITY_GROUP_DESCRIPTION: "launch-wizard-6 created via GitHub Actions"
  VPC_ID: vpc-0d1bf1da3a43aa0bd
  EIP_ALLOCATION_ID: eipalloc-0cedaf69bf3cb0685
  ECR_ROLE_NAME: ec2-ecr-role

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::575327645493:role/ec2-admin-role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$ECR_REPOSITORY:$TAG .
          docker push $REGISTRY/$ECR_REPOSITORY:$TAG

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ env.public_ip }} << EOF
          set -e

          export AWS_REGION=${{ env.AWS_REGION }}

          sudo apt-get update -y
          sudo apt-get install -y docker.io unzip awscli nginx certbot python3-certbot-nginx

          sudo systemctl start docker
          sudo systemctl enable docker

          sudo docker stop ${CONTAINER_NAME} || true
          sudo docker rm ${CONTAINER_NAME} || true
          sudo docker system prune -af || true

          aws ecr get-login-password --region $AWS_REGION \
            | sudo docker login --username AWS --password-stdin 575327645493.dkr.ecr.us-east-1.amazonaws.com

          sudo docker pull 575327645493.dkr.ecr.us-east-1.amazonaws.com/${ECR_REPOSITORY}:${{ github.sha }}

          sudo tee /etc/systemd/system/${CONTAINER_NAME}.service > /dev/null << 'EOF'
          [Unit]
          Description=Calculator API Container
          After=docker.service
          Requires=docker.service

          [Service]
          Restart=always
          ExecStart=/usr/bin/docker run --rm --name calculator-cont \
            -p 9000:9000 \
            575327645493.dkr.ecr.us-east-1.amazonaws.com/calculator-repo:${{ github.sha }}
          ExecStop=/usr/bin/docker stop calculator-cont

          [Install]
          WantedBy=multi-user.target
          EOF

          sudo systemctl daemon-reload
          sudo systemctl enable calculator-cont
          sudo systemctl restart calculator-cont
          EOF
